# Generated by Django 4.2.1 on 2023-07-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegnonveg', '0002_foods_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='user',
        ),
    ]
