# Generated by Django 4.2.1 on 2023-07-11 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('artists', models.TextField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('img', models.ImageField(upload_to='Images')),
                ('audio', models.FileField(upload_to='Audio')),
            ],
        ),
    ]
